use_frameworks!

platform :ios, '9.0'

target 'MySecondCzriLibrary_Example' do
  pod 'MySecondCzriLibrary', :path => '../'

  target 'MySecondCzriLibrary_Tests' do
    inherit! :search_paths

    
  end
end
